meta_product_name: "Etix"
meta_title: "Etix Be More Swift And Smart"
meta_description: "Etix provides quick services to register your vehicle!"
meta_image: "background.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
